### ISSUE TITLE
Keywords in function call identifiers

### ISSUE THREAD

**Issue by TimePath** [vkostyukov/kotlin-sublime-package#4]
Keywords in function call identifiers result in mis-parsing.  

Example: `eval("answer=42")` which contains `val`
- `eval("answer` is seen as an identifier set to `42`
- The rest of the document is seen as a string because of `")`

This also happens with other words such as `class`ify, `object`ion and `trait`or

**Comment by vkostyukov** [comment]
Thanks for the bug report @TimePath! Do you mind to make a PR with a fix? I'm not sure I will have a time to look into this.

**Comment by TimePath** [comment]
I'm not familiar the way tmLanguage files work, coming up with a patch may take quite a while. This bug isn't too critical for me, just something I noticed when viewing kotlin code on github instead of IntelliJ (github uses this repository for syntax highlighting)

**Comment by vkostyukov** [comment]
This should be fixed in #20.
