### ISSUE TITLE
Something weird happens with strings

### ISSUE THREAD

**Issue by shadowfacts** [vkostyukov/kotlin-sublime-package#8]
See [this file](https://github.com/Magneticraft-Team/Magneticraft/blob/91f82ab6e983900473796a8e36a0e9b55d942b79/src/main/kotlin/com/cout970/magneticraft/registry/OreDictionary.kt)

I'm not sure what specifically is caused this as I'm unable to reproduce it using a smaller example

**Comment by vkostyukov** [comment]
This should be fixed by #20.
